import csv
from pathlib import Path


BASE = Path(__file__).resolve().parent / "Data"


DRIVER_HEADERS = [
    "Manufacturer",
    "Release Year",
    "Model Name",
    "Category",
    "CC",
    "Standard Loft",
    "Face Material",
    "Adjustability",
    "Weight System",
    "Weight Range",
    "Cost (MSRP)",
    "Stock Length",
    "Swing Weight",
    "Target Player Profile",
    "Spin Profile",
    "Bias",
    "Offset",
    "Left Handed",
]

FAIRWAY_HEADERS = [
    "Manufacturer",
    "Year",
    "Model Name",
    "Release Year",
    "Category",
    "CC",
    "Standard Loft",
    "Face Material",
    "Adjustability",
    "Weight System",
    "Weight Range",
    "Cost (MSRP)",
    "Stock Length",
    "Swing Weight",
    "Target Player Profile",
    "Spin Profile",
    "Bias",
    "Offset",
    "Left Handed",
]

IRON_HEADERS = [
    "Manufacturer",
    "Year",
    "Model",
    "Category",
    "Head Material (Body/Face)",
    "Loft Array (4-PW)",
    "7i Loft / Lie",
    "Topline / Blade (7i)",
    "Finish Options",
    "Price (7pc)",
    "Stock Length",
    "Swing Weight",
    "Target Player Profile",
    "Spin Profile",
    "Bias",
    "Offset",
    "Left Handed",
]


DRIVER_NEW = [
    {"Manufacturer": "TaylorMade", "Release Year": "2024", "Model Name": "Qi10", "Category": "All-Around Distance", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "60X Carbon Twist Face", "Adjustability": "+/- 2.0", "Weight System": "Inertia Generator", "Weight Range": "Fixed", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Release Year": "2023", "Model Name": "Stealth 2", "Category": "All-Around Distance", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "60X Carbon Twist Face", "Adjustability": "+/- 2.0", "Weight System": "Inertia Generator", "Weight Range": "Fixed", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Release Year": "2022", "Model Name": "Stealth", "Category": "Distance", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "60X Carbon Twist Face", "Adjustability": "+/- 2.0", "Weight System": "Inertia Generator", "Weight Range": "Fixed", "Cost (MSRP)": "$579", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Release Year": "2021", "Model Name": "SIM2", "Category": "Distance", "CC": "460", "Standard Loft": "8, 9, 10.5", "Face Material": "Forged Ring + SIM Inertia", "Adjustability": "+/- 2.0", "Weight System": "Inertia Generator", "Weight Range": "Fixed", "Cost (MSRP)": "$529", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid-Low", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Release Year": "2020", "Model Name": "SIM", "Category": "Aerodynamic Distance", "CC": "460", "Standard Loft": "8, 9, 10.5", "Face Material": "Titanium / Twist Face", "Adjustability": "+/- 2.0", "Weight System": "Sliding Track", "Weight Range": "Adjustable", "Cost (MSRP)": "$549", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "5-15 HCP", "Spin Profile": "Low-Mid", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Release Year": "2024", "Model Name": "Paradym Ai Smoke Max", "Category": "Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "Ai Smart Face", "Adjustability": "+/- 2.0", "Weight System": "Rear Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Release Year": "2023", "Model Name": "Paradym", "Category": "All-Around Performance", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "Jailbreak AI + 360 Carbon", "Adjustability": "+/- 2.0", "Weight System": "Rear Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Release Year": "2022", "Model Name": "Rogue ST Max", "Category": "Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "Jailbreak ST + AI Face", "Adjustability": "+/- 2.0", "Weight System": "Tungsten Speed Cartridge", "Weight Range": "Fixed", "Cost (MSRP)": "$549", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Release Year": "2021", "Model Name": "Epic Max", "Category": "Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "Jailbreak AI Speed Frame", "Adjustability": "+/- 2.0", "Weight System": "Sliding Rear Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$529", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "10+ HCP", "Spin Profile": "Mid-High", "Bias": "Adjustable", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Release Year": "2020", "Model Name": "Mavrik", "Category": "Distance", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "Flash Face SS20", "Adjustability": "+/- 2.0", "Weight System": "Fixed Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$499", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Release Year": "2024", "Model Name": "GT2", "Category": "Maximum Forgiveness", "CC": "460", "Standard Loft": "8, 9, 10.5, 11.5", "Face Material": "Seamless Thermoform Crown", "Adjustability": "+/- 1.5", "Weight System": "Rear Weight", "Weight Range": "Interchangeable", "Cost (MSRP)": "$649", "Stock Length": '45.5"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Release Year": "2023", "Model Name": "TSR2", "Category": "Speed and Stability", "CC": "460", "Standard Loft": "8, 9, 10, 11", "Face Material": "ATI 425 Titanium", "Adjustability": "+/- 1.5", "Weight System": "Rear Weight", "Weight Range": "Interchangeable", "Cost (MSRP)": "$599", "Stock Length": '45.5"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Release Year": "2022", "Model Name": "TSR3", "Category": "Precision Control", "CC": "460", "Standard Loft": "8, 9, 10, 11", "Face Material": "ATI 425 Titanium", "Adjustability": "+/- 1.5", "Weight System": "SureFit CG Track", "Weight Range": "Adjustable", "Cost (MSRP)": "$599", "Stock Length": '45.5"', "Swing Weight": "D4", "Target Player Profile": "0-10 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Release Year": "2021", "Model Name": "TSi3", "Category": "Tour Performance", "CC": "460", "Standard Loft": "8, 9, 10", "Face Material": "ATI 425 Aerospace Titanium", "Adjustability": "+/- 1.5", "Weight System": "SureFit CG Track", "Weight Range": "Adjustable", "Cost (MSRP)": "$549", "Stock Length": '45.5"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Release Year": "2020", "Model Name": "TSi2", "Category": "Forgiveness", "CC": "460", "Standard Loft": "8, 9, 10, 11", "Face Material": "ATI 425 Aerospace Titanium", "Adjustability": "+/- 1.5", "Weight System": "Rear Weight", "Weight Range": "Interchangeable", "Cost (MSRP)": "$549", "Stock Length": '45.5"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2025", "Model Name": "G440 SFT", "Category": "Draw Bias", "CC": "460", "Standard Loft": "10.5, 12", "Face Material": "Forged VFT Titanium", "Adjustability": "+/- 1.5", "Weight System": "Heel/Back Adjustable Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D2", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2024", "Model Name": "G430 Max 10K", "Category": "Maximum MOI", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "Forged Face / Spinsistency", "Adjustability": "+/- 1.5", "Weight System": "Fixed Extreme Rear Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2023", "Model Name": "G430 Max", "Category": "Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "Forged Face / Spinsistency", "Adjustability": "+/- 1.5", "Weight System": "Moveable Back Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$579", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2022", "Model Name": "G425 Max", "Category": "Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "T9S+ Forged Face", "Adjustability": "+/- 1.5", "Weight System": "26g Back Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$529", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2021", "Model Name": "G425 LST", "Category": "Low Spin", "CC": "445", "Standard Loft": "9, 10.5", "Face Material": "T9S+ Forged Face", "Adjustability": "+/- 1.5", "Weight System": "Fixed Rear Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$529", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Fade Bias", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2024", "Model Name": "Darkspeed X", "Category": "All-Around Performance", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "PWRSHELL H.O.T. Face", "Adjustability": "+/- 1.5", "Weight System": "Forward/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$549", "Stock Length": '45.5"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2023", "Model Name": "AeroJet", "Category": "Speed", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "PWRSHELL H.O.T. Face", "Adjustability": "+/- 1.5", "Weight System": "PWR-BRIDGE", "Weight Range": "Fixed", "Cost (MSRP)": "$549", "Stock Length": '45.5"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2022", "Model Name": "LTDx", "Category": "Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "H.O.T. Face Insert", "Adjustability": "+/- 1.5", "Weight System": "PWR-COR", "Weight Range": "Fixed", "Cost (MSRP)": "$499", "Stock Length": '45.5"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2021", "Model Name": "RADSpeed", "Category": "Speed", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "CNC Infinity Face", "Adjustability": "+/- 1.5", "Weight System": "Radial Weighting", "Weight Range": "Fixed", "Cost (MSRP)": "$449", "Stock Length": '45.5"', "Swing Weight": "D3", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid-Low", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2020", "Model Name": "SpeedZone", "Category": "Distance", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "CNC Milled Face", "Adjustability": "+/- 1.5", "Weight System": "Front/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$449", "Stock Length": '45.5"', "Swing Weight": "D3", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid-Low", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PXG", "Release Year": "2024", "Model Name": "0311 Black Ops", "Category": "Tour Performance", "CC": "460", "Standard Loft": "8, 9, 10.5, 12", "Face Material": "AMF Face Technology", "Adjustability": "+/- 1.5", "Weight System": "3-Port Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$599", "Stock Length": '45.5"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid-Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Srixon", "Release Year": "2025", "Model Name": "ZXi", "Category": "Versatile Performance", "CC": "460", "Standard Loft": "9, 10.5", "Face Material": "i-FLEX Titanium Face", "Adjustability": "+/- 1.5", "Weight System": "Swappable Heel/Toe Weights", "Weight Range": "10g/4g", "Cost (MSRP)": "$549", "Stock Length": '45.25"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid-Low", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
]

# Expanded submodels and variants (2020-2025) for major lineups.
DRIVER_NEW.extend([
    {"Manufacturer": "TaylorMade", "Release Year": "2024", "Model Name": "Qi10 LS", "Category": "Low Spin", "CC": "460", "Standard Loft": "8, 9, 10.5", "Face Material": "60X Carbon Twist Face", "Adjustability": "+/- 2.0", "Weight System": "Forward CG", "Weight Range": "Adjustable", "Cost (MSRP)": "$629", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Release Year": "2024", "Model Name": "Qi10 Max", "Category": "Maximum Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "60X Carbon Twist Face", "Adjustability": "+/- 2.0", "Weight System": "Rear High-MOI", "Weight Range": "Fixed", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "10+ HCP", "Spin Profile": "Mid-High", "Bias": "Neutral", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Release Year": "2023", "Model Name": "Stealth 2 Plus", "Category": "Tour Low Spin", "CC": "460", "Standard Loft": "8, 9, 10.5", "Face Material": "60X Carbon Twist Face", "Adjustability": "+/- 2.0", "Weight System": "Sliding Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$629", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Release Year": "2023", "Model Name": "Stealth 2 HD", "Category": "Draw Bias", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "60X Carbon Twist Face", "Adjustability": "+/- 2.0", "Weight System": "Heel Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D2", "Target Player Profile": "15+ HCP", "Spin Profile": "High", "Bias": "Draw Bias", "Offset": "Moderate", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Release Year": "2022", "Model Name": "Stealth Plus", "Category": "Tour Low Spin", "CC": "460", "Standard Loft": "8, 9, 10.5", "Face Material": "60X Carbon Twist Face", "Adjustability": "+/- 2.0", "Weight System": "Sliding Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$579", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Release Year": "2022", "Model Name": "Stealth HD", "Category": "Draw Bias", "CC": "460", "Standard Loft": "10.5, 12", "Face Material": "60X Carbon Twist Face", "Adjustability": "+/- 2.0", "Weight System": "Heel Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$579", "Stock Length": '45.75"', "Swing Weight": "D2", "Target Player Profile": "15+ HCP", "Spin Profile": "High", "Bias": "Draw Bias", "Offset": "Moderate", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Release Year": "2024", "Model Name": "Paradym Ai Smoke Max D", "Category": "Draw Bias", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "Ai Smart Face", "Adjustability": "+/- 2.0", "Weight System": "Heel Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "12+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Release Year": "2024", "Model Name": "Paradym Ai Smoke Max LS", "Category": "Low Spin", "CC": "460", "Standard Loft": "8, 9, 10.5", "Face Material": "Ai Smart Face", "Adjustability": "+/- 2.0", "Weight System": "Front/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Release Year": "2024", "Model Name": "Paradym Ai Smoke Triple Diamond", "Category": "Tour Performance", "CC": "450", "Standard Loft": "8, 9, 10.5", "Face Material": "Ai Smart Face", "Adjustability": "+/- 2.0", "Weight System": "Front/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$599", "Stock Length": '45.5"', "Swing Weight": "D4", "Target Player Profile": "0-5 HCP", "Spin Profile": "Very Low", "Bias": "Fade", "Offset": "None", "Left Handed": "No"},
    {"Manufacturer": "Callaway", "Release Year": "2023", "Model Name": "Paradym X", "Category": "High Launch Draw", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "Jailbreak AI + 360 Carbon", "Adjustability": "+/- 2.0", "Weight System": "Back/Heel Bias", "Weight Range": "Fixed", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D2", "Target Player Profile": "10+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Release Year": "2023", "Model Name": "Paradym Triple Diamond", "Category": "Tour Low Spin", "CC": "450", "Standard Loft": "8, 9, 10.5", "Face Material": "Jailbreak AI + 360 Carbon", "Adjustability": "+/- 2.0", "Weight System": "Front/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$599", "Stock Length": '45.5"', "Swing Weight": "D4", "Target Player Profile": "0-5 HCP", "Spin Profile": "Very Low", "Bias": "Fade", "Offset": "None", "Left Handed": "No"},
    {"Manufacturer": "Callaway", "Release Year": "2022", "Model Name": "Rogue ST Max D", "Category": "Draw Bias", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "Jailbreak ST + AI Face", "Adjustability": "+/- 2.0", "Weight System": "Heel Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$549", "Stock Length": '45.75"', "Swing Weight": "D2", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Release Year": "2022", "Model Name": "Rogue ST Max LS", "Category": "Low Spin", "CC": "460", "Standard Loft": "9, 10.5", "Face Material": "Jailbreak ST + AI Face", "Adjustability": "+/- 2.0", "Weight System": "Front/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$549", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Release Year": "2024", "Model Name": "GT3", "Category": "Precision and Control", "CC": "460", "Standard Loft": "8, 9, 10.5, 11.5", "Face Material": "Seamless Thermoform Crown", "Adjustability": "+/- 1.5", "Weight System": "SureFit CG Track", "Weight Range": "Adjustable", "Cost (MSRP)": "$649", "Stock Length": '45.5"', "Swing Weight": "D3", "Target Player Profile": "0-10 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Release Year": "2024", "Model Name": "GT4", "Category": "Low Spin Compact", "CC": "430", "Standard Loft": "8, 9, 10", "Face Material": "Seamless Thermoform Crown", "Adjustability": "+/- 1.5", "Weight System": "Front/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$649", "Stock Length": '45.5"', "Swing Weight": "D4", "Target Player Profile": "0-5 HCP", "Spin Profile": "Lowest", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Release Year": "2023", "Model Name": "TSR3", "Category": "Precision Control", "CC": "460", "Standard Loft": "8, 9, 10, 11", "Face Material": "ATI 425 Titanium", "Adjustability": "+/- 1.5", "Weight System": "SureFit CG Track", "Weight Range": "Adjustable", "Cost (MSRP)": "$599", "Stock Length": '45.5"', "Swing Weight": "D4", "Target Player Profile": "0-10 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Release Year": "2023", "Model Name": "TSR4", "Category": "Lowest Spin", "CC": "430", "Standard Loft": "8, 9, 10", "Face Material": "ATI 425 Titanium", "Adjustability": "+/- 1.5", "Weight System": "Dual CG", "Weight Range": "Adjustable", "Cost (MSRP)": "$599", "Stock Length": '45.5"', "Swing Weight": "D4", "Target Player Profile": "0-5 HCP", "Spin Profile": "Lowest", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2025", "Model Name": "G440 MAX", "Category": "All-Around Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "Forged VFT Titanium", "Adjustability": "+/- 1.5", "Weight System": "Back Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2025", "Model Name": "G440 LST", "Category": "Low Spin", "CC": "450", "Standard Loft": "9, 10.5", "Face Material": "Forged VFT Titanium", "Adjustability": "+/- 1.5", "Weight System": "Forward CG", "Weight Range": "Adjustable", "Cost (MSRP)": "$599", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2023", "Model Name": "G430 LST", "Category": "Low Spin", "CC": "440", "Standard Loft": "9, 10.5", "Face Material": "Forged Face / Spinsistency", "Adjustability": "+/- 1.5", "Weight System": "Back Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$579", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Fade Bias", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2024", "Model Name": "Darkspeed LS", "Category": "Low Spin", "CC": "460", "Standard Loft": "8, 9, 10.5", "Face Material": "PWRSHELL H.O.T. Face", "Adjustability": "+/- 1.5", "Weight System": "Forward Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$549", "Stock Length": '45.5"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2024", "Model Name": "Darkspeed Max", "Category": "Maximum Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "PWRSHELL H.O.T. Face", "Adjustability": "+/- 1.5", "Weight System": "Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$549", "Stock Length": '45.5"', "Swing Weight": "D2", "Target Player Profile": "12+ HCP", "Spin Profile": "Mid-High", "Bias": "Neutral", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2023", "Model Name": "AeroJet LS", "Category": "Low Spin", "CC": "457", "Standard Loft": "8, 9, 10.5", "Face Material": "PWRSHELL H.O.T. Face", "Adjustability": "+/- 1.5", "Weight System": "Front/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$549", "Stock Length": '45.5"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2023", "Model Name": "AeroJet Max", "Category": "Draw Bias Forgiveness", "CC": "460", "Standard Loft": "10.5, 12", "Face Material": "PWRSHELL H.O.T. Face", "Adjustability": "+/- 1.5", "Weight System": "Heel/Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$549", "Stock Length": '45.5"', "Swing Weight": "D2", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "PXG", "Release Year": "2024", "Model Name": "0311 Black Ops Tour-1", "Category": "Tour Compact", "CC": "450", "Standard Loft": "8, 9, 10.5", "Face Material": "AMF Face Technology", "Adjustability": "+/- 1.5", "Weight System": "3-Port Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$599", "Stock Length": '45.5"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Srixon", "Release Year": "2025", "Model Name": "ZXi LS", "Category": "Low Spin", "CC": "450", "Standard Loft": "8.5, 9.5, 10.5", "Face Material": "i-FLEX Titanium Face", "Adjustability": "+/- 1.5", "Weight System": "Forward CG", "Weight Range": "Adjustable", "Cost (MSRP)": "$549", "Stock Length": '45.25"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Srixon", "Release Year": "2025", "Model Name": "ZXi Max", "Category": "Maximum Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "i-FLEX Titanium Face", "Adjustability": "+/- 1.5", "Weight System": "Rear Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$549", "Stock Length": '45.25"', "Swing Weight": "D2", "Target Player Profile": "10+ HCP", "Spin Profile": "Mid", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
])


FAIRWAY_NEW = [
    {"Manufacturer": "TaylorMade", "Year": "2024", "Model Name": "Qi10", "Release Year": "2024", "Category": "All-Around", "CC": "180", "Standard Loft": "15, 18, 21", "Face Material": "C300 Steel", "Adjustability": "Fixed", "Weight System": "Speed Pocket", "Weight Range": "Fixed", "Cost (MSRP)": "$349", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2023", "Model Name": "Stealth 2", "Release Year": "2023", "Category": "Distance", "CC": "185", "Standard Loft": "15, 16.5, 18, 21", "Face Material": "3D Carbon Crown / C300 Face", "Adjustability": "Fixed", "Weight System": "Inverted Cone + Speed Pocket", "Weight Range": "Fixed", "Cost (MSRP)": "$349", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2022", "Model Name": "Stealth", "Release Year": "2022", "Category": "Distance", "CC": "185", "Standard Loft": "15, 18, 21", "Face Material": "C300 Steel", "Adjustability": "Fixed", "Weight System": "V Steel Sole", "Weight Range": "Fixed", "Cost (MSRP)": "$329", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "5-20 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2021", "Model Name": "SIM2 Max", "Release Year": "2021", "Category": "Forgiveness", "CC": "190", "Standard Loft": "15, 18, 21", "Face Material": "C300 Steel", "Adjustability": "Fixed", "Weight System": "V Steel + Thru-Slot", "Weight Range": "Fixed", "Cost (MSRP)": "$299", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "10+ HCP", "Spin Profile": "Mid-High", "Bias": "Slight Draw", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2020", "Model Name": "SIM Max", "Release Year": "2020", "Category": "Forgiveness", "CC": "190", "Standard Loft": "15, 19, 22", "Face Material": "C300 Steel", "Adjustability": "Fixed", "Weight System": "V Steel Sole", "Weight Range": "Fixed", "Cost (MSRP)": "$299", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "10+ HCP", "Spin Profile": "Mid-High", "Bias": "Slight Draw", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2024", "Model Name": "Paradym Ai Smoke Max", "Release Year": "2024", "Category": "All-Around", "CC": "175", "Standard Loft": "15, 16.5, 18", "Face Material": "Ai Smart Face", "Adjustability": "+/- 2.0", "Weight System": "Tungsten Speed Cartridge", "Weight Range": "Fixed", "Cost (MSRP)": "$349", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2023", "Model Name": "Paradym", "Release Year": "2023", "Category": "All-Around", "CC": "175", "Standard Loft": "15, 16.5, 18, 21", "Face Material": "Forged Carbon / AI Face", "Adjustability": "+/- 2.0", "Weight System": "Jailbreak Batwing", "Weight Range": "Fixed", "Cost (MSRP)": "$349", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2022", "Model Name": "Rogue ST Max", "Release Year": "2022", "Category": "Forgiveness", "CC": "180", "Standard Loft": "15, 18, 21", "Face Material": "A.I. Face Cup", "Adjustability": "+/- 2.0", "Weight System": "Tungsten Speed Cartridge", "Weight Range": "Fixed", "Cost (MSRP)": "$329", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid-High", "Bias": "Neutral", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2021", "Model Name": "Epic Speed", "Release Year": "2021", "Category": "Distance", "CC": "173", "Standard Loft": "15, 18", "Face Material": "Flash Face SS21", "Adjustability": "+/- 2.0", "Weight System": "Jailbreak AI Velocity", "Weight Range": "Fixed", "Cost (MSRP)": "$299", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid-Low", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2020", "Model Name": "Mavrik", "Release Year": "2020", "Category": "Distance", "CC": "174", "Standard Loft": "15, 18", "Face Material": "Flash Face SS20", "Adjustability": "+/- 2.0", "Weight System": "Fixed Sole Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$299", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2024", "Model Name": "GT2", "Release Year": "2024", "Category": "High Launch", "CC": "180", "Standard Loft": "13.5, 15, 16.5, 18", "Face Material": "Forged L-Cup", "Adjustability": "+/- 1.5", "Weight System": "Rear Weight", "Weight Range": "Interchangeable", "Cost (MSRP)": "$349", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2023", "Model Name": "TSR2", "Release Year": "2023", "Category": "Speed and Stability", "CC": "175", "Standard Loft": "13.5, 15, 16.5, 18, 21", "Face Material": "Forged Carpenter Steel", "Adjustability": "+/- 1.5", "Weight System": "Rear Weight", "Weight Range": "Interchangeable", "Cost (MSRP)": "$349", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2022", "Model Name": "TSR3", "Release Year": "2022", "Category": "Precision", "CC": "175", "Standard Loft": "15, 16.5, 18", "Face Material": "Forged Carpenter Steel", "Adjustability": "+/- 1.5", "Weight System": "SureFit CG Track", "Weight Range": "Adjustable", "Cost (MSRP)": "$349", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-10 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2021", "Model Name": "TSi2", "Release Year": "2021", "Category": "Forgiveness", "CC": "175", "Standard Loft": "13.5, 15, 16.5, 18, 21", "Face Material": "ATI 425 Face", "Adjustability": "+/- 1.5", "Weight System": "Rear Weight", "Weight Range": "Interchangeable", "Cost (MSRP)": "$299", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2020", "Model Name": "TSi3", "Release Year": "2020", "Category": "Tour Performance", "CC": "175", "Standard Loft": "13.5, 15, 16.5", "Face Material": "ATI 425 Face", "Adjustability": "+/- 1.5", "Weight System": "SureFit CG Track", "Weight Range": "Adjustable", "Cost (MSRP)": "$299", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2024", "Model Name": "G430 Max 10K", "Release Year": "2024", "Category": "Maximum MOI", "CC": "174", "Standard Loft": "15, 18, 21", "Face Material": "Maraging Steel", "Adjustability": "+/- 1.5", "Weight System": "Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$349", "Stock Length": '43.0"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2023", "Model Name": "G430 Max", "Release Year": "2023", "Category": "All-Around", "CC": "174", "Standard Loft": "15, 18, 21", "Face Material": "Maraging Steel", "Adjustability": "+/- 1.5", "Weight System": "Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$349", "Stock Length": '43.0"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
]

FAIRWAY_NEW.extend([
    {"Manufacturer": "TaylorMade", "Year": "2024", "Model Name": "Qi10 Tour", "Release Year": "2024", "Category": "Tour Low Spin", "CC": "170", "Standard Loft": "15, 18", "Face Material": "Titanium/C300", "Adjustability": "+/- 2.0", "Weight System": "Sliding Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$449", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2024", "Model Name": "Qi10 Max", "Release Year": "2024", "Category": "Maximum Forgiveness", "CC": "190", "Standard Loft": "15, 18, 21", "Face Material": "C300 Steel", "Adjustability": "Fixed", "Weight System": "Rear CG", "Weight Range": "Fixed", "Cost (MSRP)": "$349", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "12+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2023", "Model Name": "Stealth 2 Plus", "Release Year": "2023", "Category": "Tour Low Spin", "CC": "170", "Standard Loft": "13.5, 15", "Face Material": "Titanium/C300", "Adjustability": "+/- 2.0", "Weight System": "Sliding Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$449", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2024", "Model Name": "Paradym Ai Smoke Max D", "Release Year": "2024", "Category": "Draw Bias", "CC": "185", "Standard Loft": "15, 18, 21", "Face Material": "Ai Smart Face", "Adjustability": "+/- 2.0", "Weight System": "Heel Bias", "Weight Range": "Fixed", "Cost (MSRP)": "$349", "Stock Length": '43.25"', "Swing Weight": "D1", "Target Player Profile": "12+ HCP", "Spin Profile": "High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2024", "Model Name": "Paradym Ai Smoke Triple Diamond", "Release Year": "2024", "Category": "Tour Low Spin", "CC": "170", "Standard Loft": "13.5, 15, 18", "Face Material": "Ai Smart Face", "Adjustability": "+/- 2.0", "Weight System": "Front/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$449", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "No"},
    {"Manufacturer": "Callaway", "Year": "2023", "Model Name": "Paradym X", "Release Year": "2023", "Category": "High Launch Draw", "CC": "185", "Standard Loft": "15, 18, 21", "Face Material": "Forged Carbon / AI Face", "Adjustability": "+/- 2.0", "Weight System": "Heel Bias", "Weight Range": "Fixed", "Cost (MSRP)": "$349", "Stock Length": '43.25"', "Swing Weight": "D1", "Target Player Profile": "12+ HCP", "Spin Profile": "High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2024", "Model Name": "GT3", "Release Year": "2024", "Category": "Precision", "CC": "175", "Standard Loft": "15, 16.5, 18", "Face Material": "Forged L-Cup", "Adjustability": "+/- 1.5", "Weight System": "SureFit CG Track", "Weight Range": "Adjustable", "Cost (MSRP)": "$349", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-10 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2023", "Model Name": "TSR3", "Release Year": "2023", "Category": "Tour Performance", "CC": "175", "Standard Loft": "13.5, 15, 16.5, 18", "Face Material": "Forged Carpenter Steel", "Adjustability": "+/- 1.5", "Weight System": "SureFit CG Track", "Weight Range": "Adjustable", "Cost (MSRP)": "$349", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-10 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2023", "Model Name": "G430 LST", "Release Year": "2023", "Category": "Low Spin", "CC": "165", "Standard Loft": "15", "Face Material": "Maraging Steel", "Adjustability": "+/- 1.5", "Weight System": "Sole Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$429", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Fade Bias", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2024", "Model Name": "Darkspeed LS", "Release Year": "2024", "Category": "Low Spin", "CC": "172", "Standard Loft": "14.5, 17.5", "Face Material": "PWRSHELL H.O.T. Face", "Adjustability": "+/- 1.5", "Weight System": "Forward/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$349", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2023", "Model Name": "AeroJet LS", "Release Year": "2023", "Category": "Low Spin", "CC": "170", "Standard Loft": "14.5, 17.5", "Face Material": "PWRSHELL H.O.T. Face", "Adjustability": "+/- 1.5", "Weight System": "Forward/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$349", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Srixon", "Year": "2025", "Model Name": "ZXi LS", "Release Year": "2025", "Category": "Low Spin", "CC": "170", "Standard Loft": "14.5, 15", "Face Material": "Ti51AF Titanium Face", "Adjustability": "+/- 1.5", "Weight System": "Forward CG", "Weight Range": "Adjustable", "Cost (MSRP)": "$329", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Srixon", "Year": "2025", "Model Name": "ZXi Max", "Release Year": "2025", "Category": "Max Forgiveness", "CC": "180", "Standard Loft": "15, 18, 21", "Face Material": "Ti51AF / Rebound Frame", "Adjustability": "Fixed", "Weight System": "Rear Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$329", "Stock Length": '43.0"', "Swing Weight": "D2", "Target Player Profile": "12+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
])


IRON_NEW = [
    {"Manufacturer": "TaylorMade", "Year": "2024", "Model": "P·770", "Category": "Players Distance", "Head Material (Body/Face)": "8620 Carbon / Forged Face", "Loft Array (4-PW)": "22.5/25.5/29/33/37/41/46", "7i Loft / Lie": "33.0° / 62.5°", "Topline / Blade (7i)": "6.5mm / 77mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,399", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-10 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2023", "Model": "P·790", "Category": "Players Distance", "Head Material (Body/Face)": "8620 Carbon / SpeedFoam Air", "Loft Array (4-PW)": "21/23.5/26.5/30.5/35/40/45", "7i Loft / Lie": "30.5° / 62.5°", "Topline / Blade (7i)": "7.2mm / 79mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,499", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Low-Mid", "Bias": "Neutral", "Offset": "Slight (2.7mm)", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2022", "Model": "Stealth", "Category": "Game Improv.", "Head Material (Body/Face)": "Cap Back / Toe Wrap", "Loft Array (4-PW)": "18.5/21/24/28/32/37/43", "7i Loft / Lie": "28.0° / 62.5°", "Topline / Blade (7i)": "8.2mm / 82mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$999", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "10+ HCP", "Spin Profile": "Low", "Bias": "Draw Bias", "Offset": "Moderate (4.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2021", "Model": "P·7MC", "Category": "Tour Cavity", "Head Material (Body/Face)": "Forged 1025 Carbon Steel", "Loft Array (4-PW)": "23/26/30/34/38/42/46", "7i Loft / Lie": "34.0° / 62.5°", "Topline / Blade (7i)": "5.3mm / 75mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,399", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.8mm)", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2020", "Model": "P·770", "Category": "Players Distance", "Head Material (Body/Face)": "Forged Hollow / Inverted Cone", "Loft Array (4-PW)": "22.5/25.5/29/33/37/41/46", "7i Loft / Lie": "33.0° / 62.5°", "Topline / Blade (7i)": "6.3mm / 77mm", "Finish Options": "Satin", "Price (7pc)": "$1,299", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-12 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.2mm)", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2024", "Model": "Apex Pro", "Category": "Players Cavity", "Head Material (Body/Face)": "Forged 1025 Carbon", "Loft Array (4-PW)": "23/26/29/33/37/41/45", "7i Loft / Lie": "33.0° / 62.0°", "Topline / Blade (7i)": "5.5mm / 76mm", "Finish Options": "Satin", "Price (7pc)": "$1,500", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "Mid-High", "Bias": "Neutral", "Offset": "Minimal (1.8mm)", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2023", "Model": "Paradym", "Category": "Players Distance", "Head Material (Body/Face)": "Forged 455 Face / Hollow", "Loft Array (4-PW)": "20.5/23/26/29/33/38/43", "7i Loft / Lie": "29.0° / 62.0°", "Topline / Blade (7i)": "7.8mm / 80mm", "Finish Options": "Chrome", "Price (7pc)": "$1,300", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Low-Mid", "Bias": "Neutral", "Offset": "Slight (2.8mm)", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2022", "Model": "Rogue ST Pro", "Category": "Players Distance", "Head Material (Body/Face)": "Hollow Body / Urethane Microspheres", "Loft Array (4-PW)": "20/23/26/30/34.5/39/44", "7i Loft / Lie": "30.0° / 62.0°", "Topline / Blade (7i)": "7.0mm / 79mm", "Finish Options": "Satin", "Price (7pc)": "$1,200", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2021", "Model": "Apex 21", "Category": "Players Distance", "Head Material (Body/Face)": "Forged 1025 / A.I. Face Cup", "Loft Array (4-PW)": "21/23.5/26.5/30.5/35/40/45", "7i Loft / Lie": "30.5° / 62.0°", "Topline / Blade (7i)": "7.0mm / 79mm", "Finish Options": "Chrome", "Price (7pc)": "$1,199", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.7mm)", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2020", "Model": "Mavrik", "Category": "Game Improv.", "Head Material (Body/Face)": "Flash Face Cup / Urethane", "Loft Array (4-PW)": "18/21/24/27/30.5/35/41.5", "7i Loft / Lie": "27.0° / 62.0°", "Topline / Blade (7i)": "8.5mm / 82mm", "Finish Options": "Chrome", "Price (7pc)": "$799", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "12+ HCP", "Spin Profile": "Low", "Bias": "Draw Bias", "Offset": "Moderate (4.2mm)", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2024", "Model": "T200", "Category": "Players Distance", "Head Material (Body/Face)": "Forged Face / Max Impact", "Loft Array (4-PW)": "21/24/27/30.5/34.5/39/43", "7i Loft / Lie": "30.5° / 63.0°", "Topline / Blade (7i)": "7.5mm / 81mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,499", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Low-Mid", "Bias": "Neutral", "Offset": "Progressive (3.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2023", "Model": "T150", "Category": "Players Distance", "Head Material (Body/Face)": "Forged 1025 / Muscle Channel", "Loft Array (4-PW)": "22/25/28/32/36/40/44", "7i Loft / Lie": "32.0° / 63.0°", "Topline / Blade (7i)": "6.5mm / 78mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,499", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-10 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2022", "Model": "T100", "Category": "Tour Player", "Head Material (Body/Face)": "Forged 1025 / Dual Cavity", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 63.0°", "Topline / Blade (7i)": "5.0mm / 74mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,399", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2021", "Model": "T200", "Category": "Players Distance", "Head Material (Body/Face)": "Forged L-Face / Max Impact", "Loft Array (4-PW)": "20/23/26/29/33/38/43", "7i Loft / Lie": "29.0° / 63.0°", "Topline / Blade (7i)": "7.4mm / 81mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,299", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Low-Mid", "Bias": "Neutral", "Offset": "Progressive (3.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2020", "Model": "T300", "Category": "Game Improv.", "Head Material (Body/Face)": "High-Strength Steel / Max Impact", "Loft Array (4-PW)": "20/23/26/29/33/38/43", "7i Loft / Lie": "29.0° / 63.0°", "Topline / Blade (7i)": "8.2mm / 82mm", "Finish Options": "Chrome", "Price (7pc)": "$999", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "12+ HCP", "Spin Profile": "Low", "Bias": "Draw Bias", "Offset": "Moderate (4.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2024", "Model": "i530", "Category": "Players Distance", "Head Material (Body/Face)": "17-4 SS / Forged Face", "Loft Array (4-PW)": "20/23/26/29.5/34/39/44.5", "7i Loft / Lie": "29.5° / 62.0°", "Topline / Blade (7i)": "7.0mm / 79mm", "Finish Options": "Hydropearl 2.0", "Price (7pc)": "$1,400", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "5-15 HCP", "Spin Profile": "Low-Mid", "Bias": "Neutral", "Offset": "Slight (2.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2023", "Model": "i230", "Category": "Players Cavity", "Head Material (Body/Face)": "431 Stainless Steel", "Loft Array (4-PW)": "22.5/26/29.5/33/37/41/45", "7i Loft / Lie": "33.0° / 62.0°", "Topline / Blade (7i)": "6.0mm / 77mm", "Finish Options": "Hydropearl 2.0", "Price (7pc)": "$1,400", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "0-10 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2022", "Model": "i525", "Category": "Players Distance", "Head Material (Body/Face)": "17-4 SS / Maraging Face", "Loft Array (4-PW)": "20.5/23.5/26.5/30/34.5/39.5/44.5", "7i Loft / Lie": "30.0° / 62.0°", "Topline / Blade (7i)": "7.2mm / 79mm", "Finish Options": "Hydropearl 2.0", "Price (7pc)": "$1,299", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "5-15 HCP", "Spin Profile": "Low-Mid", "Bias": "Neutral", "Offset": "Slight (2.7mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2024", "Model": "JPX 923 Hot Metal", "Category": "Game Improv.", "Head Material (Body/Face)": "Chromoly 4335 / Cup Face", "Loft Array (4-PW)": "19/22/25/28.5/33/37.5/42.5", "7i Loft / Lie": "28.5° / 62.0°", "Topline / Blade (7i)": "8.0mm / 81mm", "Finish Options": "Chrome", "Price (7pc)": "$1,000", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "12+ HCP", "Spin Profile": "Low", "Bias": "Draw", "Offset": "Progressive (4.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2023", "Model": "AeroJet", "Category": "Game Improv.", "Head Material (Body/Face)": "Hollow Body / PWRSHELL", "Loft Array (4-PW)": "19/21.5/24/27.5/32/37/42", "7i Loft / Lie": "27.5° / 62.0°", "Topline / Blade (7i)": "8.2mm / 82mm", "Finish Options": "Chrome", "Price (7pc)": "$999", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "10+ HCP", "Spin Profile": "Low", "Bias": "Draw Bias", "Offset": "Moderate (4.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "PXG", "Year": "2023", "Model": "0311 P Gen6", "Category": "Players Distance", "Head Material (Body/Face)": "Forged 8620 / HT1770 Face", "Loft Array (4-PW)": "21/24/27/30/34/39/44", "7i Loft / Lie": "30.0° / 62.5°", "Topline / Blade (7i)": "6.5mm / 78mm", "Finish Options": "Chrome / Xtreme Dark", "Price (7pc)": "$1,299", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "0-10 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "Srixon", "Year": "2025", "Model": "ZXi5", "Category": "Players Distance", "Head Material (Body/Face)": "Forged Carbon / SUP10 Face", "Loft Array (4-PW)": "22/24/27/31/35/39/44", "7i Loft / Lie": "31.0° / 62.0°", "Topline / Blade (7i)": "7.0mm / 79mm", "Finish Options": "Tour Satin", "Price (7pc)": "$1,200", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.8mm)", "Left Handed": "✓"},
    {"Manufacturer": "Takomo", "Year": "2025", "Model": "201", "Category": "Players Cavity", "Head Material (Body/Face)": "Forged S20C Carbon", "Loft Array (4-PW)": "22/25/28/31/35/40/45", "7i Loft / Lie": "31.0° / 62.5°", "Topline / Blade (7i)": "6.0mm / 75mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$589", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "0-10 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Minimal (2.0mm)", "Left Handed": "✓"},
]

IRON_NEW.extend([
    {"Manufacturer": "TaylorMade", "Year": "2024", "Model": "P·790", "Category": "Players Distance", "Head Material (Body/Face)": "8620 Carbon / SpeedFoam Air", "Loft Array (4-PW)": "21/23.5/26.5/30.5/35/40/45", "7i Loft / Lie": "30.5° / 62.5°", "Topline / Blade (7i)": "7.2mm / 79mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,499", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Low-Mid", "Bias": "Neutral", "Offset": "Slight (2.7mm)", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2024", "Model": "P·7CB", "Category": "Tour Cavity", "Head Material (Body/Face)": "Compact Forged 1025", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 62.5°", "Topline / Blade (7i)": "5.5mm / 74mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,399", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-3 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "TaylorMade", "Year": "2023", "Model": "P·770", "Category": "Players Distance", "Head Material (Body/Face)": "8620 Carbon / Forged 4140 Face", "Loft Array (4-PW)": "22.5/25.5/29/33/37/41/46", "7i Loft / Lie": "33.0° / 62.5°", "Topline / Blade (7i)": "6.5mm / 77mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,399", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-10 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2024", "Model": "Apex CB", "Category": "Tour Cavity", "Head Material (Body/Face)": "Forged 1025 Carbon", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 62.0°", "Topline / Blade (7i)": "5.0mm / 74mm", "Finish Options": "Satin", "Price (7pc)": "$1,500", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.6mm)", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2024", "Model": "Apex DCB", "Category": "Game Improv.", "Head Material (Body/Face)": "Forged 1025 / Hollow", "Loft Array (4-PW)": "20/23/26/30/34/39/44", "7i Loft / Lie": "30.0° / 62.0°", "Topline / Blade (7i)": "8.5mm / 82mm", "Finish Options": "Chrome", "Price (7pc)": "$1,250", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "12+ HCP", "Spin Profile": "Low", "Bias": "Draw Bias", "Offset": "Moderate (4.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "Callaway", "Year": "2023", "Model": "Apex Pro", "Category": "Players Cavity", "Head Material (Body/Face)": "Forged 1025 Carbon", "Loft Array (4-PW)": "23/26/29/33/37/41/45", "7i Loft / Lie": "33.0° / 62.0°", "Topline / Blade (7i)": "5.5mm / 76mm", "Finish Options": "Satin", "Price (7pc)": "$1,450", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "Mid-High", "Bias": "Neutral", "Offset": "Minimal (1.8mm)", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2024", "Model": "T150", "Category": "Players Distance", "Head Material (Body/Face)": "Forged 1025 / Hollow Muscle", "Loft Array (4-PW)": "22/25/28/32/36/40/44", "7i Loft / Lie": "32.0° / 63.0°", "Topline / Blade (7i)": "6.5mm / 78mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,499", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-10 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2024", "Model": "T350", "Category": "Game Improv.", "Head Material (Body/Face)": "High Strength Steel / Max Impact", "Loft Array (4-PW)": "20/23/26/29/33/38/43", "7i Loft / Lie": "29.0° / 63.0°", "Topline / Blade (7i)": "8.5mm / 83mm", "Finish Options": "Chrome", "Price (7pc)": "$1,299", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "12+ HCP", "Spin Profile": "Low", "Bias": "Draw Bias", "Offset": "Moderate (4.2mm)", "Left Handed": "✓"},
    {"Manufacturer": "Titleist", "Year": "2023", "Model": "T100", "Category": "Tour Player", "Head Material (Body/Face)": "Forged 1025 / Dual Cavity", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 63.0°", "Topline / Blade (7i)": "5.0mm / 74mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,499", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2024", "Model": "Blueprint S", "Category": "Tour Player", "Head Material (Body/Face)": "Forged 8620 Carbon Steel", "Loft Array (4-PW)": "23/26/29.5/33/37/41/45", "7i Loft / Lie": "33.0° / 62.0°", "Topline / Blade (7i)": "4.8mm / 74mm", "Finish Options": "Hydropearl 2.0", "Price (7pc)": "$1,500", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "0-3 HCP", "Spin Profile": "High", "Bias": "None", "Offset": "Minimal (1.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2024", "Model": "G430", "Category": "Game Improv.", "Head Material (Body/Face)": "17-4 Stainless / VFT", "Loft Array (4-PW)": "19/22/25.5/29/33/37/41", "7i Loft / Lie": "29.0° / 62.0°", "Topline / Blade (7i)": "8.2mm / 82mm", "Finish Options": "Hydropearl 2.0", "Price (7pc)": "$1,100", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "10+ HCP", "Spin Profile": "Low-Mid", "Bias": "Draw Bias", "Offset": "Moderate (4.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2024", "Model": "KING Tour", "Category": "Tour Player", "Head Material (Body/Face)": "Forged 1025 Carbon Steel", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 62.5°", "Topline / Blade (7i)": "5.0mm / 75mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,300", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "0-5 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2024", "Model": "Darkspeed", "Category": "Game Improv.", "Head Material (Body/Face)": "Hollow Body / PWRSHELL", "Loft Array (4-PW)": "20/23/26/29.5/34/39/44", "7i Loft / Lie": "29.5° / 62.0°", "Topline / Blade (7i)": "8.0mm / 82mm", "Finish Options": "Chrome", "Price (7pc)": "$1,100", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "10+ HCP", "Spin Profile": "Low-Mid", "Bias": "Draw Bias", "Offset": "Moderate (4.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "PXG", "Year": "2024", "Model": "0311 XP Gen6", "Category": "Game Improv.", "Head Material (Body/Face)": "Forged 8620 / HT1770 Face", "Loft Array (4-PW)": "19/22/25/28.5/33/38/43", "7i Loft / Lie": "28.5° / 62.5°", "Topline / Blade (7i)": "8.0mm / 82mm", "Finish Options": "Chrome / Xtreme Dark", "Price (7pc)": "$1,299", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "10+ HCP", "Spin Profile": "Low", "Bias": "Draw Bias", "Offset": "Moderate (3.8mm)", "Left Handed": "✓"},
    {"Manufacturer": "Srixon", "Year": "2025", "Model": "ZXi7", "Category": "Tour Cavity", "Head Material (Body/Face)": "Forged 1020 Carbon", "Loft Array (4-PW)": "23/26/29/33/37/41/46", "7i Loft / Lie": "33.0° / 62.0°", "Topline / Blade (7i)": "5.5mm / 76mm", "Finish Options": "Tour Satin", "Price (7pc)": "$1,200", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (2.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "Takomo", "Year": "2025", "Model": "101", "Category": "Game Improv.", "Head Material (Body/Face)": "431 Stainless Hollow", "Loft Array (4-PW)": "20/22.5/25.5/29/33/38/43", "7i Loft / Lie": "29.0° / 62.0°", "Topline / Blade (7i)": "8.0mm / 81mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$489", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "10+ HCP", "Spin Profile": "Low-Mid", "Bias": "Neutral / Draw", "Offset": "Moderate (4.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "Takomo", "Year": "2025", "Model": "301 CB", "Category": "Tour Player", "Head Material (Body/Face)": "Forged S20C Carbon", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 62.5°", "Topline / Blade (7i)": "4.8mm / 73mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$649", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.5mm)", "Left Handed": "✓"},
])

# Gap-fill focus: Cobra and PING historical coverage.
DRIVER_NEW.extend([
    {"Manufacturer": "PING", "Release Year": "2020", "Model Name": "G410 Plus", "Category": "All-Around Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "T9S+ Forged Face", "Adjustability": "+/- 1.5", "Weight System": "Moveable Back Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$499", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2020", "Model Name": "G410 LST", "Category": "Low Spin", "CC": "450", "Standard Loft": "9, 10.5", "Face Material": "T9S+ Forged Face", "Adjustability": "+/- 1.5", "Weight System": "Back Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$499", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Fade Bias", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2021", "Model Name": "G425 Max", "Category": "All-Around Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "T9S+ Forged Face", "Adjustability": "+/- 1.5", "Weight System": "26g Back Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$529", "Stock Length": '45.75"', "Swing Weight": "D3", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2021", "Model Name": "G425 SFT", "Category": "Draw Bias", "CC": "460", "Standard Loft": "10.5, 12", "Face Material": "T9S+ Forged Face", "Adjustability": "+/- 1.5", "Weight System": "Draw-Biased Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$529", "Stock Length": '45.75"', "Swing Weight": "D2", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2022", "Model Name": "G425 SFT", "Category": "Draw Bias", "CC": "460", "Standard Loft": "10.5, 12", "Face Material": "T9S+ Forged Face", "Adjustability": "+/- 1.5", "Weight System": "Draw-Biased Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$529", "Stock Length": '45.75"', "Swing Weight": "D2", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2024", "Model Name": "G430 LST", "Category": "Low Spin", "CC": "440", "Standard Loft": "9, 10.5", "Face Material": "Forged Face / Spinsistency", "Adjustability": "+/- 1.5", "Weight System": "Moveable Back Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$579", "Stock Length": '45.75"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Fade Bias", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Release Year": "2024", "Model Name": "G430 SFT", "Category": "Draw Bias", "CC": "460", "Standard Loft": "10.5, 12", "Face Material": "Forged Face / Spinsistency", "Adjustability": "+/- 1.5", "Weight System": "Draw-Biased Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$579", "Stock Length": '45.75"', "Swing Weight": "D2", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2020", "Model Name": "SpeedZone Xtreme", "Category": "Maximum Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "CNC Milled Face", "Adjustability": "+/- 1.5", "Weight System": "Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$449", "Stock Length": '45.5"', "Swing Weight": "D2", "Target Player Profile": "12+ HCP", "Spin Profile": "Mid-High", "Bias": "Neutral", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2021", "Model Name": "RADSpeed XB", "Category": "Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "CNC Infinity Face", "Adjustability": "+/- 1.5", "Weight System": "Rear Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$449", "Stock Length": '45.5"', "Swing Weight": "D3", "Target Player Profile": "10+ HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2021", "Model Name": "RADSpeed XD", "Category": "Draw Bias", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "CNC Infinity Face", "Adjustability": "+/- 1.5", "Weight System": "Heel/Rear Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$449", "Stock Length": '45.5"', "Swing Weight": "D2", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Moderate", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2022", "Model Name": "LTDx LS", "Category": "Low Spin", "CC": "460", "Standard Loft": "9, 10.5", "Face Material": "H.O.T. Face Insert", "Adjustability": "+/- 1.5", "Weight System": "Forward/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$499", "Stock Length": '45.5"', "Swing Weight": "D4", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Release Year": "2022", "Model Name": "LTDx Max", "Category": "Maximum Forgiveness", "CC": "460", "Standard Loft": "9, 10.5, 12", "Face Material": "H.O.T. Face Insert", "Adjustability": "+/- 1.5", "Weight System": "Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$499", "Stock Length": '45.5"', "Swing Weight": "D2", "Target Player Profile": "12+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
])

FAIRWAY_NEW.extend([
    {"Manufacturer": "PING", "Year": "2020", "Model Name": "G410 Plus", "Release Year": "2020", "Category": "All-Around", "CC": "176", "Standard Loft": "14.5, 17.5, 20.5", "Face Material": "Maraging Steel", "Adjustability": "+/- 1.0", "Weight System": "Fixed Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$299", "Stock Length": '43.0"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2020", "Model Name": "G410 SFT", "Release Year": "2020", "Category": "Draw Bias", "CC": "180", "Standard Loft": "16, 19, 22", "Face Material": "Maraging Steel", "Adjustability": "+/- 1.0", "Weight System": "Heel Bias", "Weight Range": "Fixed", "Cost (MSRP)": "$299", "Stock Length": '43.0"', "Swing Weight": "D1", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2021", "Model Name": "G425 Max", "Release Year": "2021", "Category": "All-Around", "CC": "176", "Standard Loft": "14.5, 17.5, 20.5", "Face Material": "Maraging Steel", "Adjustability": "+/- 1.5", "Weight System": "Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$299", "Stock Length": '43.0"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2021", "Model Name": "G425 SFT", "Release Year": "2021", "Category": "Draw Bias", "CC": "180", "Standard Loft": "16, 19, 22", "Face Material": "Maraging Steel", "Adjustability": "+/- 1.5", "Weight System": "Heel Bias", "Weight Range": "Fixed", "Cost (MSRP)": "$299", "Stock Length": '43.0"', "Swing Weight": "D1", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2022", "Model Name": "G425 Max", "Release Year": "2022", "Category": "All-Around", "CC": "176", "Standard Loft": "14.5, 17.5, 20.5", "Face Material": "Maraging Steel", "Adjustability": "+/- 1.5", "Weight System": "Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$299", "Stock Length": '43.0"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2022", "Model Name": "G425 LST", "Release Year": "2022", "Category": "Low Spin", "CC": "167", "Standard Loft": "14.5", "Face Material": "Maraging Steel", "Adjustability": "+/- 1.5", "Weight System": "Compact CG", "Weight Range": "Fixed", "Cost (MSRP)": "$399", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Fade Bias", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2024", "Model Name": "G430 SFT", "Release Year": "2024", "Category": "Draw Bias", "CC": "176", "Standard Loft": "16, 19, 22", "Face Material": "Maraging Steel", "Adjustability": "+/- 1.5", "Weight System": "Heel Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$349", "Stock Length": '43.0"', "Swing Weight": "D1", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2025", "Model Name": "G440 LST", "Release Year": "2025", "Category": "Low Spin", "CC": "165", "Standard Loft": "15", "Face Material": "Titanium/Tungsten", "Adjustability": "+/- 1.5", "Weight System": "Sole Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$429", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Fade Bias", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2025", "Model Name": "G440 SFT", "Release Year": "2025", "Category": "Draw Bias", "CC": "176", "Standard Loft": "16, 19", "Face Material": "Maraging Steel", "Adjustability": "+/- 1.5", "Weight System": "Heel Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$349", "Stock Length": '43.0"', "Swing Weight": "D1", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2020", "Model Name": "SpeedZone", "Release Year": "2020", "Category": "All-Around", "CC": "174", "Standard Loft": "14.5, 17.5", "Face Material": "CNC Milled Face", "Adjustability": "+/- 1.5", "Weight System": "Front/Back Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$249", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2021", "Model Name": "RADSpeed", "Release Year": "2021", "Category": "All-Around", "CC": "174", "Standard Loft": "14.5, 17.5", "Face Material": "CNC Infinity Face", "Adjustability": "+/- 1.5", "Weight System": "Front/Back Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$279", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2021", "Model Name": "RADSpeed XB", "Release Year": "2021", "Category": "Forgiveness", "CC": "180", "Standard Loft": "15, 18, 21", "Face Material": "CNC Infinity Face", "Adjustability": "Fixed", "Weight System": "Rear Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$249", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "10+ HCP", "Spin Profile": "Mid-High", "Bias": "Neutral", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2022", "Model Name": "LTDx LS", "Release Year": "2022", "Category": "Low Spin", "CC": "170", "Standard Loft": "14.5, 17.5", "Face Material": "H.O.T. Face", "Adjustability": "+/- 1.5", "Weight System": "Front/Back Weights", "Weight Range": "Adjustable", "Cost (MSRP)": "$299", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2022", "Model Name": "LTDx Max", "Release Year": "2022", "Category": "Maximum Forgiveness", "CC": "180", "Standard Loft": "15, 18, 21", "Face Material": "H.O.T. Face", "Adjustability": "+/- 1.5", "Weight System": "Rear Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$299", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "12+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2025", "Model Name": "DS-Adapt LS", "Release Year": "2025", "Category": "Low Spin", "CC": "175", "Standard Loft": "14.5, 17.5", "Face Material": "Titanium / H.O.T. Face", "Adjustability": "+/- 1.5", "Weight System": "FutureFit33", "Weight Range": "Adjustable", "Cost (MSRP)": "$379", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Adjustable", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2025", "Model Name": "DS-Adapt Max", "Release Year": "2025", "Category": "Maximum Forgiveness", "CC": "185", "Standard Loft": "15.5, 18.5, 21.5", "Face Material": "H.O.T. Face / PWR-BRIDGE", "Adjustability": "+/- 1.5", "Weight System": "FutureFit33", "Weight Range": "Adjustable", "Cost (MSRP)": "$329", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "12+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
])

IRON_NEW.extend([
    {"Manufacturer": "PING", "Year": "2020", "Model": "G710", "Category": "Game Improv.", "Head Material (Body/Face)": "17-4 SS / Maraging Face", "Loft Array (4-PW)": "18/21/24/27.5/31/35.5/41", "7i Loft / Lie": "27.5° / 62.0°", "Topline / Blade (7i)": "8.8mm / 83mm", "Finish Options": "Hydropearl Stealth", "Price (7pc)": "$1,250", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "12+ HCP", "Spin Profile": "Low", "Bias": "Draw Bias", "Offset": "Moderate (4.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2020", "Model": "i500", "Category": "Players Distance", "Head Material (Body/Face)": "17-4 SS / Maraging Face", "Loft Array (4-PW)": "19/22/25/28.5/32/36/41", "7i Loft / Lie": "28.5° / 62.0°", "Topline / Blade (7i)": "7.2mm / 79mm", "Finish Options": "Chrome", "Price (7pc)": "$1,100", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "5-15 HCP", "Spin Profile": "Low-Mid", "Bias": "Neutral", "Offset": "Slight (2.8mm)", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2021", "Model": "i59", "Category": "Tour Player", "Head Material (Body/Face)": "Forged 1025 / AlumiCore", "Loft Array (4-PW)": "23/26/30/34/38/42/46", "7i Loft / Lie": "34.0° / 62.0°", "Topline / Blade (7i)": "5.0mm / 74mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,750", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "0-5 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.8mm)", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2021", "Model": "G425", "Category": "Game Improv.", "Head Material (Body/Face)": "17-4 Stainless / VFT", "Loft Array (4-PW)": "20/22.5/26/29.5/34/39/44", "7i Loft / Lie": "29.5° / 62.0°", "Topline / Blade (7i)": "8.2mm / 82mm", "Finish Options": "Hydropearl 2.0", "Price (7pc)": "$900", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "10+ HCP", "Spin Profile": "Low-Mid", "Bias": "Draw Bias", "Offset": "Moderate (4.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2025", "Model": "G440 Irons", "Category": "Game Improv.", "Head Material (Body/Face)": "17-4 Stainless Steel / VFT", "Loft Array (4-PW)": "20/23/26/29.5/34/39/44", "7i Loft / Lie": "29.5° / 62.0°", "Topline / Blade (7i)": "8.0mm / 82mm", "Finish Options": "Hydropearl 2.0", "Price (7pc)": "$1,100", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "10+ HCP", "Spin Profile": "Low-Mid", "Bias": "Neutral / Draw", "Offset": "Moderate (4.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "PING", "Year": "2025", "Model": "i230", "Category": "Players Cavity", "Head Material (Body/Face)": "431 Stainless Steel", "Loft Array (4-PW)": "22.5/26/29.5/33/37/41/45", "7i Loft / Lie": "33.0° / 62.0°", "Topline / Blade (7i)": "6.0mm / 77mm", "Finish Options": "Hydropearl 2.0", "Price (7pc)": "$1,400", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "0-10 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2020", "Model": "KING Forged Tec", "Category": "Players Distance", "Head Material (Body/Face)": "Forged 1025 / Pwrshell", "Loft Array (4-PW)": "21/24/27/31/35/40/45", "7i Loft / Lie": "31.0° / 62.5°", "Topline / Blade (7i)": "6.8mm / 78mm", "Finish Options": "Chrome", "Price (7pc)": "$1,099", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.6mm)", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2021", "Model": "KING Tour MIM", "Category": "Tour Player", "Head Material (Body/Face)": "Metal Injection Molded 1025", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 62.5°", "Topline / Blade (7i)": "5.0mm / 75mm", "Finish Options": "Satin", "Price (7pc)": "$1,299", "Stock Length": '37.0" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.6mm)", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2022", "Model": "KING LTDx", "Category": "Game Improv.", "Head Material (Body/Face)": "Hollow Body / PWRSHELL", "Loft Array (4-PW)": "19/21.5/24/27.5/32/37/42", "7i Loft / Lie": "27.5° / 62.0°", "Topline / Blade (7i)": "8.2mm / 82mm", "Finish Options": "Chrome", "Price (7pc)": "$999", "Stock Length": '37.0" (7i)', "Swing Weight": "D1", "Target Player Profile": "10+ HCP", "Spin Profile": "Low", "Bias": "Draw Bias", "Offset": "Moderate (4.0mm)", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2022", "Model": "KING Forged Tec", "Category": "Players Distance", "Head Material (Body/Face)": "Forged 1025 / Pwrshell", "Loft Array (4-PW)": "21/23.5/26.5/30/34.5/39.5/44.5", "7i Loft / Lie": "30.0° / 62.5°", "Topline / Blade (7i)": "7.0mm / 79mm", "Finish Options": "Chrome", "Price (7pc)": "$1,199", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-12 HCP", "Spin Profile": "Low-Mid", "Bias": "Neutral", "Offset": "Slight (2.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2025", "Model": "KING Tour", "Category": "Tour Player", "Head Material (Body/Face)": "Forged 1025 Carbon Steel", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 62.5°", "Topline / Blade (7i)": "5.0mm / 75mm", "Finish Options": "Satin Chrome", "Price (7pc)": "$1,300", "Stock Length": '37.0" (7i)', "Swing Weight": "D2", "Target Player Profile": "0-5 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.5mm)", "Left Handed": "✓"},
])

# Additional lineup depth per user feedback:
# - Cobra fairways: add LS/MAX/XD-type branches where applicable.
# - Mizuno irons: enforce JPX vs Mizuno Pro alternation with multiple models.
FAIRWAY_NEW.extend([
    {"Manufacturer": "Cobra", "Year": "2020", "Model Name": "SpeedZone Tour", "Release Year": "2020", "Category": "Low Spin", "CC": "170", "Standard Loft": "14.5, 17.5", "Face Material": "CNC Milled Face", "Adjustability": "+/- 1.5", "Weight System": "Forward/Back Weight", "Weight Range": "Adjustable", "Cost (MSRP)": "$279", "Stock Length": '43.0"', "Swing Weight": "D3", "Target Player Profile": "0-8 HCP", "Spin Profile": "Low", "Bias": "Neutral/Fade", "Offset": "None", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2022", "Model Name": "Air-X", "Release Year": "2022", "Category": "Lightweight Draw", "CC": "185", "Standard Loft": "16, 19, 22", "Face Material": "H.O.T. Face", "Adjustability": "Fixed", "Weight System": "Lightweight Build", "Weight Range": "Fixed", "Cost (MSRP)": "$249", "Stock Length": '43.25"', "Swing Weight": "D0", "Target Player Profile": "15+ HCP (Slow Swing)", "Spin Profile": "High", "Bias": "Draw Bias", "Offset": "Moderate", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2023", "Model Name": "AeroJet Max", "Release Year": "2023", "Category": "Draw Bias Forgiveness", "CC": "185", "Standard Loft": "15, 18, 21", "Face Material": "PWRSHELL H.O.T. Face", "Adjustability": "Fixed", "Weight System": "Heel/Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$329", "Stock Length": '43.25"', "Swing Weight": "D1", "Target Player Profile": "15+ HCP", "Spin Profile": "Mid-High", "Bias": "Draw Bias", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2024", "Model Name": "Darkspeed Max", "Release Year": "2024", "Category": "Maximum Forgiveness", "CC": "185", "Standard Loft": "15, 18, 21", "Face Material": "PWRSHELL H.O.T. Face", "Adjustability": "Fixed", "Weight System": "Back Weight", "Weight Range": "Fixed", "Cost (MSRP)": "$329", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "12+ HCP", "Spin Profile": "Mid-High", "Bias": "Neutral/Draw", "Offset": "Slight", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2025", "Model Name": "DS-Adapt Max-D", "Release Year": "2025", "Category": "Draw Bias", "CC": "185", "Standard Loft": "15.5, 18.5", "Face Material": "H.O.T. Face / PWR-BRIDGE", "Adjustability": "+/- 1.5", "Weight System": "FutureFit33 Heel Bias", "Weight Range": "Adjustable", "Cost (MSRP)": "$329", "Stock Length": '43.25"', "Swing Weight": "D1", "Target Player Profile": "15+ HCP (Slicer)", "Spin Profile": "High", "Bias": "Draw Bias", "Offset": "Moderate", "Left Handed": "✓"},
    {"Manufacturer": "Cobra", "Year": "2025", "Model Name": "DS-Adapt X", "Release Year": "2025", "Category": "All-Around", "CC": "180", "Standard Loft": "15, 18", "Face Material": "H.O.T. Face / PWR-BRIDGE", "Adjustability": "+/- 1.5", "Weight System": "FutureFit33", "Weight Range": "Adjustable", "Cost (MSRP)": "$329", "Stock Length": '43.25"', "Swing Weight": "D2", "Target Player Profile": "All Skill Levels", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "None", "Left Handed": "✓"},
])

IRON_NEW.extend([
    {"Manufacturer": "Mizuno", "Year": "2020", "Model": "JPX 921 Forged", "Category": "Players Distance", "Head Material (Body/Face)": "1025 Boron Forged", "Loft Array (4-PW)": "22/25/28/32/36/41/46", "7i Loft / Lie": "32.0° / 62.0°", "Topline / Blade (7i)": "6.5mm / 78mm", "Finish Options": "Pearl Brush", "Price (7pc)": "$1,200", "Stock Length": '37.0\" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-12 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.4mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2020", "Model": "JPX 921 Hot Metal", "Category": "Game Improv.", "Head Material (Body/Face)": "Chromoly 4140M", "Loft Array (4-PW)": "19/22/25/28.5/33/37.5/42.5", "7i Loft / Lie": "28.5° / 62.0°", "Topline / Blade (7i)": "8.0mm / 81mm", "Finish Options": "Chrome", "Price (7pc)": "$875", "Stock Length": '37.0\" (7i)', "Swing Weight": "D1", "Target Player Profile": "12+ HCP", "Spin Profile": "Low", "Bias": "Draw", "Offset": "Progressive (4.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2021", "Model": "Mizuno Pro 221", "Category": "Tour Blade", "Head Material (Body/Face)": "1025E Grain Flow Forged", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 61.5°", "Topline / Blade (7i)": "4.7mm / 72mm", "Finish Options": "Satin", "Price (7pc)": "$1,400", "Stock Length": '37.0\" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-3 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.2mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2021", "Model": "Mizuno Pro 223", "Category": "Players Cavity", "Head Material (Body/Face)": "1025E Forged / Chromoly", "Loft Array (4-PW)": "22/25/28/32/36/40/44", "7i Loft / Lie": "32.0° / 61.5°", "Topline / Blade (7i)": "5.8mm / 76mm", "Finish Options": "Satin", "Price (7pc)": "$1,400", "Stock Length": '37.0\" (7i)', "Swing Weight": "D2", "Target Player Profile": "0-8 HCP", "Spin Profile": "Mid-High", "Bias": "Neutral", "Offset": "Minimal (1.8mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2021", "Model": "Mizuno Pro 225", "Category": "Players Distance", "Head Material (Body/Face)": "Chromoly Forged Hollow", "Loft Array (4-PW)": "22/25/28/31/35/40/45", "7i Loft / Lie": "31.0° / 61.5°", "Topline / Blade (7i)": "6.6mm / 78mm", "Finish Options": "Satin", "Price (7pc)": "$1,400", "Stock Length": '37.0\" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.4mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2022", "Model": "JPX 923 Forged", "Category": "Players Distance", "Head Material (Body/Face)": "1025 Boron Forged", "Loft Array (4-PW)": "21/24/27/31/35/39/44", "7i Loft / Lie": "31.0° / 62.0°", "Topline / Blade (7i)": "6.5mm / 78mm", "Finish Options": "Pearl Brush", "Price (7pc)": "$1,300", "Stock Length": '37.0\" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-12 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2022", "Model": "JPX 923 Tour", "Category": "Tour Player", "Head Material (Body/Face)": "1025E Grain Flow Forged", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 61.5°", "Topline / Blade (7i)": "5.0mm / 74mm", "Finish Options": "Satin", "Price (7pc)": "$1,300", "Stock Length": '37.0\" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-5 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.6mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2023", "Model": "Mizuno Pro 241", "Category": "Tour Blade", "Head Material (Body/Face)": "1025E Grain Flow Forged", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 61.5°", "Topline / Blade (7i)": "4.6mm / 72mm", "Finish Options": "Satin", "Price (7pc)": "$1,500", "Stock Length": '37.0\" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-3 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.1mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2023", "Model": "Mizuno Pro 243", "Category": "Players Cavity", "Head Material (Body/Face)": "1025E Forged / Chromoly", "Loft Array (4-PW)": "22/25/28/32/36/40/44", "7i Loft / Lie": "32.0° / 61.5°", "Topline / Blade (7i)": "5.7mm / 76mm", "Finish Options": "Satin", "Price (7pc)": "$1,500", "Stock Length": '37.0\" (7i)', "Swing Weight": "D2", "Target Player Profile": "0-8 HCP", "Spin Profile": "Mid-High", "Bias": "Neutral", "Offset": "Minimal (1.8mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2023", "Model": "Mizuno Pro 245", "Category": "Players Distance", "Head Material (Body/Face)": "Chromoly Forged Hollow", "Loft Array (4-PW)": "21/24/27/30/34/39/44", "7i Loft / Lie": "30.0° / 61.5°", "Topline / Blade (7i)": "6.6mm / 78mm", "Finish Options": "Satin", "Price (7pc)": "$1,500", "Stock Length": '37.0\" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.5mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2025", "Model": "Mizuno Pro 241", "Category": "Tour Blade", "Head Material (Body/Face)": "1025E Grain Flow Forged", "Loft Array (4-PW)": "24/27/30/34/38/42/46", "7i Loft / Lie": "34.0° / 61.5°", "Topline / Blade (7i)": "4.6mm / 72mm", "Finish Options": "Satin", "Price (7pc)": "$1,500", "Stock Length": '37.0\" (7i)', "Swing Weight": "D3", "Target Player Profile": "0-3 HCP", "Spin Profile": "High", "Bias": "Neutral", "Offset": "Minimal (1.1mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2025", "Model": "Mizuno Pro 243", "Category": "Players Cavity", "Head Material (Body/Face)": "1025E Forged / Chromoly", "Loft Array (4-PW)": "22/25/28/32/36/40/44", "7i Loft / Lie": "32.0° / 61.5°", "Topline / Blade (7i)": "5.7mm / 76mm", "Finish Options": "Satin", "Price (7pc)": "$1,500", "Stock Length": '37.0\" (7i)', "Swing Weight": "D2", "Target Player Profile": "0-8 HCP", "Spin Profile": "Mid-High", "Bias": "Neutral", "Offset": "Minimal (1.8mm)", "Left Handed": "✓"},
    {"Manufacturer": "Mizuno", "Year": "2025", "Model": "Mizuno Pro 245", "Category": "Players Distance", "Head Material (Body/Face)": "Chromoly Forged Hollow", "Loft Array (4-PW)": "21/24/27/30/34/39/44", "7i Loft / Lie": "30.0° / 61.5°", "Topline / Blade (7i)": "6.6mm / 78mm", "Finish Options": "Satin", "Price (7pc)": "$1,500", "Stock Length": '37.0\" (7i)', "Swing Weight": "D2", "Target Player Profile": "5-15 HCP", "Spin Profile": "Mid", "Bias": "Neutral", "Offset": "Slight (2.5mm)", "Left Handed": "✓"},
])

def merge_rows(path: Path, headers: list[str], new_rows: list[dict], key_fields: list[str]) -> None:
    existing = []
    if path.exists():
        with path.open("r", encoding="utf-8-sig", newline="") as f:
            existing = list(csv.DictReader(f))

    seen = {(tuple(r.get(k, "") for k in key_fields)) for r in existing}
    for row in new_rows:
        key = tuple(row.get(k, "") for k in key_fields)
        if key not in seen:
            existing.append(row)
            seen.add(key)

    # Keep newest years first, preserve non-year records at bottom.
    def year_key(r: dict) -> int:
        y = r.get("Release Year") or r.get("Year") or ""
        return int(y) if y.isdigit() else -1

    existing.sort(key=lambda r: (year_key(r), r.get("Manufacturer", ""), r.get("Model Name", r.get("Model", ""))), reverse=True)

    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=headers)
        writer.writeheader()
        for row in existing:
            writer.writerow({h: row.get(h, "") for h in headers})


if __name__ == "__main__":
    merge_rows(
        BASE / "Golf Comparison - Drivers.csv",
        DRIVER_HEADERS,
        DRIVER_NEW,
        ["Manufacturer", "Release Year", "Model Name"],
    )
    merge_rows(
        BASE / "Golf Comparison - Fairway.csv",
        FAIRWAY_HEADERS,
        FAIRWAY_NEW,
        ["Manufacturer", "Release Year", "Model Name"],
    )
    merge_rows(
        BASE / "Golf Comparison - Irons.csv",
        IRON_HEADERS,
        IRON_NEW,
        ["Manufacturer", "Year", "Model"],
    )
    print("Added 2020-2025 rows to drivers, fairways, and irons.")
